//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generador_Jason.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="service.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Generador_Jason.service.HelloWorldResponse HelloWorld(Generador_Jason.service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Generador_Jason.service.HelloWorldResponse> HelloWorldAsync(Generador_Jason.service.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento url del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFileToFtp", ReplyAction="*")]
        Generador_Jason.service.UploadFileToFtpResponse UploadFileToFtp(Generador_Jason.service.UploadFileToFtpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFileToFtp", ReplyAction="*")]
        System.Threading.Tasks.Task<Generador_Jason.service.UploadFileToFtpResponse> UploadFileToFtpAsync(Generador_Jason.service.UploadFileToFtpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Generador_Jason.service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Generador_Jason.service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Generador_Jason.service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Generador_Jason.service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileToFtpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileToFtp", Namespace="http://tempuri.org/", Order=0)]
        public Generador_Jason.service.UploadFileToFtpRequestBody Body;
        
        public UploadFileToFtpRequest() {
        }
        
        public UploadFileToFtpRequest(Generador_Jason.service.UploadFileToFtpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileToFtpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filePath;
        
        public UploadFileToFtpRequestBody() {
        }
        
        public UploadFileToFtpRequestBody(string url, string filePath) {
            this.url = url;
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileToFtpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileToFtpResponse", Namespace="http://tempuri.org/", Order=0)]
        public Generador_Jason.service.UploadFileToFtpResponseBody Body;
        
        public UploadFileToFtpResponse() {
        }
        
        public UploadFileToFtpResponse(Generador_Jason.service.UploadFileToFtpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileToFtpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileToFtpResult;
        
        public UploadFileToFtpResponseBody() {
        }
        
        public UploadFileToFtpResponseBody(string UploadFileToFtpResult) {
            this.UploadFileToFtpResult = UploadFileToFtpResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Generador_Jason.service.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Generador_Jason.service.WebServiceSoap>, Generador_Jason.service.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Generador_Jason.service.HelloWorldResponse Generador_Jason.service.WebServiceSoap.HelloWorld(Generador_Jason.service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Generador_Jason.service.HelloWorldRequest inValue = new Generador_Jason.service.HelloWorldRequest();
            inValue.Body = new Generador_Jason.service.HelloWorldRequestBody();
            Generador_Jason.service.HelloWorldResponse retVal = ((Generador_Jason.service.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Generador_Jason.service.HelloWorldResponse> Generador_Jason.service.WebServiceSoap.HelloWorldAsync(Generador_Jason.service.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Generador_Jason.service.HelloWorldResponse> HelloWorldAsync() {
            Generador_Jason.service.HelloWorldRequest inValue = new Generador_Jason.service.HelloWorldRequest();
            inValue.Body = new Generador_Jason.service.HelloWorldRequestBody();
            return ((Generador_Jason.service.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Generador_Jason.service.UploadFileToFtpResponse Generador_Jason.service.WebServiceSoap.UploadFileToFtp(Generador_Jason.service.UploadFileToFtpRequest request) {
            return base.Channel.UploadFileToFtp(request);
        }
        
        public string UploadFileToFtp(string url, string filePath) {
            Generador_Jason.service.UploadFileToFtpRequest inValue = new Generador_Jason.service.UploadFileToFtpRequest();
            inValue.Body = new Generador_Jason.service.UploadFileToFtpRequestBody();
            inValue.Body.url = url;
            inValue.Body.filePath = filePath;
            Generador_Jason.service.UploadFileToFtpResponse retVal = ((Generador_Jason.service.WebServiceSoap)(this)).UploadFileToFtp(inValue);
            return retVal.Body.UploadFileToFtpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Generador_Jason.service.UploadFileToFtpResponse> Generador_Jason.service.WebServiceSoap.UploadFileToFtpAsync(Generador_Jason.service.UploadFileToFtpRequest request) {
            return base.Channel.UploadFileToFtpAsync(request);
        }
        
        public System.Threading.Tasks.Task<Generador_Jason.service.UploadFileToFtpResponse> UploadFileToFtpAsync(string url, string filePath) {
            Generador_Jason.service.UploadFileToFtpRequest inValue = new Generador_Jason.service.UploadFileToFtpRequest();
            inValue.Body = new Generador_Jason.service.UploadFileToFtpRequestBody();
            inValue.Body.url = url;
            inValue.Body.filePath = filePath;
            return ((Generador_Jason.service.WebServiceSoap)(this)).UploadFileToFtpAsync(inValue);
        }
    }
}
